### ISSUE TITLE
composite primary keys

### ISSUE THREAD

**Issue by sm2017** [Kaltsoon/sequelize-cursor-pagination#40]
```js
const options = {
  methodName: 'paginate',
  primaryKeyField: 'id',
};
```

How can I set `primaryKeyField` for composite primary keys?

**Comment by Kaltsoon** [comment]
With composite primary keys, you can have one of the keys as the `primaryKeyField` and other should be present in the `order`. The `primaryKeyField`option is used to ensure that table's primary key is in the `order` (see [here](https://github.com/Kaltsoon/sequelize-cursor-pagination/blob/62964e6207ffb970433fe0dde7766bda9ed67872/src/utils.js#L52)). Because at the moment the `primaryKeyField` option doesn't support composite primary keys you'll have to include it in the `order` per query basis.

**Comment by Kaltsoon** [comment]
Version 2.3.0 now supports composite primary keys with `primaryKeyField: ['key1', 'key2']`. Enjoy!
